version = 0.1
[default.deploy.parameters]
capabilities = "CAPABILITY_IAM CAPABILITY_AUTO_EXPAND CAPABILITY_NAMED_IAM"
stack_name = "pruebilla"
resolve_s3 = true
s3_prefix = "pruebilla"
region = "us-east-1"
disable_rollback = true
parameter_overrides = "UserPoolName=\"MyUserPool\" UserPoolClientName=\"MyUserPoolClient\" AppSyncApiName=\"MyGraphQLApi\" DynamoDBName=\"MyDBPet\""
image_repositories = []
