Parameters:
  ArnRoleAppSyncCloudWatch:
    Type: String
    Description: The Arn of RoleAppSyncCloudWatch
  ArnRoleAppSyncDynamoDB:
    Type: String
    Description: The Arn of RoleAppSyncDynamoDB
  APIName:
    Type: String
    Default: GraphQLApi2
    Description: The name of API
  DynamoDBName:
    Type: String
    Default: MyDBPet
    Description: The DynamoDB Name

Resources:
  GraphQLApi2:
    Type: AWS::AppSync::GraphQLApi
    Properties:
      Name: !Ref APIName
      AuthenticationType: API_KEY
      LogConfig:
        CloudWatchLogsRoleArn: !Ref ArnRoleAppSyncCloudWatch
        ExcludeVerboseContent: FALSE
        FieldLogLevel: ALL
  Schema:
    Type: AWS::AppSync::GraphQLSchema
    Properties:
      ApiId: !GetAtt GraphQLApi2.ApiId
      DefinitionS3Location: ./schemas/schema2.graphql
  DynamoDBDataSource:
    Type: AWS::AppSync::DataSource
    Properties:
      ApiId: !GetAtt GraphQLApi2.ApiId
      Name: !Ref APIName
      Type: AMAZON_DYNAMODB
      ServiceRoleArn: !Ref ArnRoleAppSyncDynamoDB
      DynamoDBConfig:
        TableName: !Ref DynamoDBName
        AwsRegion: !Sub ${AWS::Region}
  CreatePetResolverForDB:
    Type: AWS::AppSync::Resolver
    Properties:
      ApiId: !GetAtt GraphQLApi2.ApiId
      DataSourceName: !GetAtt DynamoDBDataSource.Name
      FieldName: createPetDB
      TypeName: Mutation
      RequestMappingTemplate: >
        {
          "version": "2017-02-28",
          "operation": "PutItem",
          "key": {
            "id": { "S": "$util.autoId()" }
          },
          "attributeValues": {
            "name": { "S": "$ctx.args.input.name" },
            "createdAt": { "S": "$util.time.nowISO8601()" },
            "updatedAt": { "S": "$util.time.nowISO8601()" }
          }
        }
      ResponseMappingTemplate: $util.toJson($ctx.result)
  GetPetByIDResolverForDB:
    Type: AWS::AppSync::Resolver
    Properties:
      ApiId: !GetAtt GraphQLApi2.ApiId
      DataSourceName: !GetAtt DynamoDBDataSource.Name
      FieldName: getPetByIdDB
      TypeName: Query
      RequestMappingTemplate: |
        {
          "version": "2017-02-28",
          "operation": "GetItem",
          "key": {
            "id": $util.dynamodb.toDynamoDBJson($ctx.args.id)
          }
        }
      ResponseMappingTemplate: $util.toJson($ctx.result)
  DeletePetResolverForDB:
    Type: AWS::AppSync::Resolver
    Properties:
      ApiId: !GetAtt GraphQLApi2.ApiId
      DataSourceName: !GetAtt DynamoDBDataSource.Name
      FieldName: deletePetDB
      TypeName: Mutation
      RequestMappingTemplate: |
        {
          "version": "2017-02-28",
          "operation": "DeleteItem",
          "key": {
            "id": $util.dynamodb.toDynamoDBJson($ctx.args.id)
          }
        }
      ResponseMappingTemplate: $util.toJson($ctx.result)
  GetAllPetsResolverForDB:
    Type: AWS::AppSync::Resolver
    Properties:
      ApiId: !GetAtt GraphQLApi2.ApiId
      DataSourceName: !GetAtt DynamoDBDataSource.Name
      FieldName: getAllPetsDB
      TypeName: Query
      RequestMappingTemplate: |
        {
          "version": "2017-02-28",
          "operation": "Scan",
          "filter": {
            "expression": "#name <> :empty",
            "expressionNames": {
              "#name": "name"
            },
            "expressionValues": {
              ":empty": {
                "S": ""
              }
            }
          }
        }
      RequestMappingTemplate: |
        {
          "version": "2017-02-28",
          "operation": "Scan",
          "filter": {
            "expression": "#name <> :empty",
            "expressionNames": {
              "#name": "name"
            },
            "expressionValues": {
              ":empty": {
                "S": ""
              }
            }
          }
        }
      ResponseMappingTemplate: |
        $util.toJson($context.result.items)
  AppSyncAPIKey:
    Type: AWS::AppSync::ApiKey
    Properties:
      ApiId: !GetAtt GraphQLApi2.ApiId

Outputs:
  APIKey:
    Description: API Key
    Value: !GetAtt AppSyncAPIKey.ApiKey
  GraphQL:
    Description: GraphQL URL
    Value: !GetAtt GraphQLApi2.GraphQLUrl

